[package]
name = "client"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.16", features = ["derive"] }
clap_derive = "4.5.13"
env_logger = "0.11.5"
log = "0.4.22"
reqwest = { version = "0.12.7", features = ["blocking", "json"] }
serde_json = "1.0.127"
tokio = "1.39.3"
