services:
  app:
    build: .
    restart: unless-stopped
    container_name: wallpaper_server
    volumes:
      - ./wallpapers_server:/usr/src/app/server/wallpapers
    networks:
      - app_network

  nginx:
    image: nginx:latest
    restart: unless-stopped
    container_name: nginx_proxy
    ports:
      - "${PORT}:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - app
    networks:
      - app_network
    environment:
      - NGINX_USER=${NGINX_USER}
      - NGINX_PASSWORD=${NGINX_PASSWORD}
    command: >
      /bin/bash -c "
      echo -n '${NGINX_USER}:' >> /etc/nginx/.htpasswd &&
      openssl passwd -apr1 '${NGINX_PASSWORD}' >> /etc/nginx/.htpasswd &&
      nginx -g 'daemon off;'
      "

networks:
  app_network:
    driver: bridge
