services:
  app:
    build: .
    container_name: wallpaper_server
    ports:
      - "4000:4000"  # Map container port 4000 to host port 4000
    volumes:
      - ./wallpapers_server:/usr/src/app/server/wallpapers
    networks:
      - app_network

  nginx:
    image: nginx:latest
    container_name: nginx_proxy
    ports:
      - "8080:80"  # Expose Nginx on port 8080
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./htpasswd:/etc/nginx/htpasswd:ro
    depends_on:
      - app
    networks:
      - app_network

networks:
  app_network:
    driver: bridge
