services:
  app:
    build: .
    restart: unless-stopped
    container_name: wallpaper_server
    volumes:
      - ./wallpapers_server:/usr/src/app/server/wallpapers
    networks:
      - app_network

  nginx:
    image: nginx:latest
    restart: unless-stopped
    container_name: nginx_proxy
    ports:
      - "8080:80"  # Change port 8080 to whatever you'd like
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./htpasswd:/etc/nginx/htpasswd:ro
    depends_on:
      - app
    networks:
      - app_network

networks:
  app_network:
    driver: bridge
